export const pricingByCategory = {
  0: [
    {
      id: 1,
      icon: "topology",
      title: "Essential Plan",
      squares: [
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
      ],
      description: "The perfect starting place for your web app or personal project.",
      tagicon: "sparkles",
      tagline: "Starter",
      isVisible: "flex",
      price: "$299",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 1-2 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Single-page website design",
        "UI/UX design with responsive layouts",
        "Responsive design across all devices",
        "1 round of revisions included",
        "Delivered in Figma file",
        "Development available at additional cost",
      ],
    },
    {
      id: 2,
      icon: "topologyStar1",
      title: "Standard Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
      ],
      description: "Everything you need to build and scale your app.",
      tagicon: "flame",
      tagline: "Popular",
      isVisible: "flex",
      price: "$599",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 3-4 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Up to 5 custom pages designed",
        "UI/UX design with modern layouts",
        "Responsive design across all devices",
        "2 rounds of revisions included",
        "Design handoff with prototype",
        "Development available at additional cost",
      ],
    },
    {
      id: 3,
      icon: "topologyStar2",
      title: "Enterprise Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
      ],
      description: "Best for large comprehensive, enterprise-level design solutions.",
      tagicon: "clockDollar",
      tagline: "Valuable",
      isVisible: "flex",
      price: "$1,499",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 5-6 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Up to 10 uniquely designed pages",
        "UI/UX strategy with wireframing",
        "Responsive design across all devices",
        "Unlimited revisions (within agreed scope)",
        "Basic on-page SEO implementation",
        "Development available at additional cost",
      ],
    },
    {
      id: 4,
      icon: "topologyStar3",
      title: "Partnership Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
      ],
      description: "Best for those who need ongoing support or have a flexible scope of work.",
      tagicon: "hourglass",
      tagline: "Limited",
      isVisible: "flex",
      price: "$2,999",
      validity: "/Per month",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: Ongoing", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Dedicated Design Leadership",
        "Senior UI/UX designer on-demand",
        "Full-scope project management",
        "Unlimited requests & refinements",
        "Regular Updates and maintenance",
        "Focused Workflow with weekly Syncs",
      ],
    },
  ],

  1: [
      {
        id: 1,
        icon: "topology",
        title: "Hobby",
        squares: [
          { size: 14, className: "text-foreground" },
          { size: 12, className: "text-ring/30" },
          { size: 12, className: "text-ring/30" },
          { size: 12, className: "text-ring/30" },
        ],
        description: "The perfect starting place for your web app or personal project.",
        tagicon: "sparkles",
        tagline: "Starter",
        isVisible: "hidden",
        surface: "bg-background",
        price: "$3,499",
        validity: "/One-time.",
        buttonVariant: "outline",
        buttonLabel: "Get Started",
        benefitIcons: ["clock", "headset"],
        benefits: ["Project timeline: 1-2 weeks", "Priority Support"],
        listTitle: "All listed features:",
        features: [
          "Single-page website design",
          "Responsive UI/UX for all devices",
          "Design system with reusable styles",  
          "1 round of design revisions",
          "404 & 500 error page included",
          "Delivered in editable design files",
        ],
        featuresIcons: [
            1,
            2,
            3,
            4,
            5,
            6,
        ]
    },
    {
        id: 2,
        icon: "topologyStar1",
        title: "Pro",
        squares: [
          { size: 12, className: "text-ring/30" },
          { size: 14, className: "text-foreground" },
          { size: 12, className: "text-ring/30" },
          { size: 12, className: "text-ring/30" },
        ],
        description: "Everything you need to build and scale your app.",
        tagicon: "flame",
        tagline: "Popular",
        isVisible: "flex",
        surface: "bg-surface",
        price: "$12,499",
        validity: "/One-time.",
        buttonVariant: "default",
        buttonLabel: "Get Started",
        benefitIcons: ["clock", "headset"],
        benefits: ["Project timeline: 3-4 weeks", "Priority Support"],
        listTitle: "All Hobby features, plus:",
        features: [
          "Multi-page website (up to 8 pages)",
          "Custom component design system",
          "Production-ready frontend build",
          "Basic on-page SEO setup",
          "2 rounds of revisions included",
          "Faster project turnaround",
          
        ],
        featuresIcons: [
            7,
            8,
            9,
            10,
            11,
            12,
        ]
    },
    {
        id: 3,
        icon: "topologyStar2",
        title: "Enterprise",
        squares: [
          { size: 12, className: "text-ring/30" },
          { size: 12, className: "text-ring/30" },
          { size: 14, className: "text-foreground" },
          { size: 12, className: "text-ring/30" },
        ],
        description: "Critical performance, scalability, and sopport for complex platforms.",
        tagicon: "clockDollar",
        tagline: "Valuable",
        isVisible: "hidden",
        surface: "bg-background",
        price: "Custom",
        validity: "",
        buttonVariant: "outline",
        buttonLabel: "Get Started",
        benefitIcons: ["clock", "headset"],
        benefits: ["Project timeline: Undefined", "Priority Support"],
        listTitle: "All Pro features, plus:",
        features: [
          "Custom application architecture",
          "Multi-region deployment & failover",
          "SLA-backed support agreement",
          "Dedicated engineering support",
          "Ongoing retainer available",
          "Custom integrations & infrastructure",
        ],
        featuresIcons: [
            13,
            14,
            15,
            16,
            17,
            18,
        ]
    },
  ],

  2: [
    {
      id: 1,
      icon: "topology",
      title: "Essential Plan",
      squares: [
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
      ],
      description: "Best for individuals and small teams seeking professional design services to establish a strong online presence.",
      tagicon: "sparkles",
      tagline: "Starter",
      isVisible: "flex",
      price: "$299",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 1-2 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Single-page website design",
        "UI/UX design with responsive layouts",
        "Responsive design across all devices",
        "1 round of revisions included",
        "Delivered in Figma file",
        "Development available at additional cost",
      ],
    },
    {
      id: 2,
      icon: "topologyStar1",
      title: "Standard Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
      ],
      description:
        "Best for medium-sized teams or startups looking to enhance their online presence and achieve their business goals.",
      tagicon: "flame",
      tagline: "Popular",
      isVisible: "flex",
      price: "$599",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 3-4 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Up to 5 custom pages designed",
        "UI/UX design with modern layouts",
        "Responsive design across all devices",
        "2 rounds of revisions included",
        "Design handoff with prototype",
        "Development available at additional cost",
      ],
    },
    {
      id: 3,
      icon: "topologyStar2",
      title: "Enterprise Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
      ],
      description:
        "Best for large teams and corporations seeking comprehensive, enterprise-level design solutions, and advanced features.",
      tagicon: "clockDollar",
      tagline: "Valuable",
      isVisible: "flex",
      price: "$1,499",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 5-6 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Up to 10 uniquely designed pages",
        "UI/UX strategy with wireframing",
        "Responsive design across all devices",
        "Unlimited revisions (within agreed scope)",
        "Basic on-page SEO implementation",
        "Development available at additional cost",
      ],
    },
    {
      id: 4,
      icon: "topologyStar3",
      title: "Partnership Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
      ],
      description:
        "Best for those who need ongoing support, handle multiple projects, or have a flexible or undefined scope of work.",
      tagicon: "hourglass",
      tagline: "Limited",
      isVisible: "flex",
      price: "$2,999",
      validity: "/Per month",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: Ongoing", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Dedicated Design Leadership",
        "Senior UI/UX designer on-demand",
        "Full-scope project management",
        "Unlimited requests & refinements",
        "Regular Updates and maintenance",
        "Focused Workflow with weekly Syncs",
      ],
    },
  ],

  3: [
    {
      id: 1,
      icon: "topology",
      title: "Essential Plan",
      squares: [
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
      ],
      description: "Best for individuals and small teams seeking professional design services to establish a strong online presence.",
      tagicon: "sparkles",
      tagline: "Starter",
      isVisible: "flex",
      price: "$299",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 1-2 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Single-page website design",
        "UI/UX design with responsive layouts",
        "Responsive design across all devices",
        "1 round of revisions included",
        "Delivered in Figma file",
        "Development available at additional cost",
      ],
    },
    {
      id: 2,
      icon: "topologyStar1",
      title: "Standard Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
      ],
      description:
        "Best for medium-sized teams or startups looking to enhance their online presence and achieve their business goals.",
      tagicon: "flame",
      tagline: "Popular",
      isVisible: "flex",
      price: "$599",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 3-4 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Up to 5 custom pages designed",
        "UI/UX design with modern layouts",
        "Responsive design across all devices",
        "2 rounds of revisions included",
        "Design handoff with prototype",
        "Development available at additional cost",
      ],
    },
    {
      id: 3,
      icon: "topologyStar2",
      title: "Enterprise Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
        { size: 12, className: "text-ring/30" },
      ],
      description:
        "Best for large teams and corporations seeking comprehensive, enterprise-level design solutions, and advanced features.",
      tagicon: "clockDollar",
      tagline: "Valuable",
      isVisible: "flex",
      price: "$1,499",
      validity: "/One time",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: 5-6 weeks", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Up to 10 uniquely designed pages",
        "UI/UX strategy with wireframing",
        "Responsive design across all devices",
        "Unlimited revisions (within agreed scope)",
        "Basic on-page SEO implementation",
        "Development available at additional cost",
      ],
    },
    {
      id: 4,
      icon: "topologyStar3",
      title: "Partnership Plan",
      squares: [
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 12, className: "text-ring/30" },
        { size: 14, className: "text-foreground" },
      ],
      description:
        "Best for those who need ongoing support, handle multiple projects, or have a flexible or undefined scope of work.",
      tagicon: "hourglass",
      tagline: "Limited",
      isVisible: "flex",
      price: "$2,999",
      validity: "/Per month",
      buttonLabel: "Start Your Project",
      benefitIcons: ["clock", "headset"],
      benefits: ["Project timeline: Ongoing", "Priority Support"],
      listTitle: "What you will get?",
      features: [
        "Dedicated Design Leadership",
        "Senior UI/UX designer on-demand",
        "Full-scope project management",
        "Unlimited requests & refinements",
        "Regular Updates and maintenance",
        "Focused Workflow with weekly Syncs",
      ],
    },
  ],
};

export default pricingByCategory;